lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_SECRET_KEY)%'
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
    token_ttl: '%env(COOKIE_TTL)%'
    encoder:
        signature_algorithm: RS512

    #https://github.com/lexik/LexikJWTAuthenticationBundle/blob/master/Resources/doc/1-configuration-reference.md#full-default-configuration
    token_extractors:
        cookie:
            enabled: true
            name: BEARER
    set_cookies:
        BEARER:
            lifetime: ~
            samesite: lax
            path: '%env(resolve:COOKIE_PATH)%'
            domain: null
            secure: '%env(resolve:COOKIE_SECURE)%'
            httpOnly: '%env(resolve:COOKIE_HTTPONLY)%'
