version: '3.8'
services:
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ~/apps/mongo:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    networks:
      - books-api-network
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    restart: on-failure
    container_name: ${PROJECT_NAME:-books-api}-php
    volumes:
      - '.:/usr/src/app'
    user: ${LOCAL_USER}
    networks:
      - books-api-network
    env_file:
      - docker.env
    
  nginx:
    image: nginx:1.19.0-alpine
    restart: on-failure
    container_name: ${PROJECT_NAME:-books-api}-nginx
    volumes:
      - './public/:/usr/src/app'
      - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
    ports:
      - '${NGINX_PORT:-9185}:80'
    depends_on:
         - php
    networks:
      - books-api-network
    env_file:
      - docker.env

networks:
  books-api-network: { }

volumes:
  books-api-postgres-data:
###> doctrine/doctrine-bundle ###
  db:
###< doctrine/doctrine-bundle ###
