<?php

namespace App\Tests\Functional;

use App\Entity\User;
use App\Repository\UserRepository;
use Faker\Factory;
use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;

abstract class ApiTestCase extends WebTestCase
{
    protected ?User $testUser = null;
    protected $faker;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->faker = Factory::create();
    }

    protected function createAuthenticatedClient($username = 'user', $password = 'password')
    {
        $client = static::createClient();

        $userRepository = static::getContainer()->get(UserRepository::class);
        $this->testUser = $userRepository->findBy(array('email' => $username));
        $client->loginUser($this->testUser);

        return $client;
    }
}
